lab10/firstapp/urls.py
from django.conf.urls import *
from django.contrib import admin
from . import views
urlpatterns = [  
  url(r'^login/', views.my_login),
  url(r'^logout/', views.my_logout),
  url(r'^Course_reg/', views.add_course),
  url(r'^add_students/', views.add_students),

]

lab10/lab10/urls.py
from django.contrib import admin
from django.conf.urls import url,include

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^firstapp/', include('firstapp.urls')),  

]

lab10/firstapp/models.py
from django.db import models
from datetime import datetime    
class courses(models.Model):
    course_name= models.CharField(max_length=10)
    count = models.IntegerField(default=0)
    def __str__(self):
      return self.course_name

class Questio(models.Model):
    question_text = models.CharField(max_length=200)
    forname = models.CharField(max_length=100)
    question_id = models.IntegerField() 
    course_name = models.CharField(max_length=10)
    def __str__(self):
        return self.question_text

class Student(models.Model):
    name = models.CharField(max_length=100)
    roll_number  = models.CharField(max_length=50)
    courses_undertaken = models.ManyToManyField(courses)
    def __str__(self):
      return self.name

class Deadline(models.Model):
    name=models.CharField(max_length=100)
    time=models.DateTimeField(default=datetime.now,blank=True)
    description=models.TextField(max_length=1000)
    def __str__(self):
        return self.name

class FeedbackForm(models.Model):
    name = models.CharField(max_length=100)
    course_name = models.CharField(max_length=100)   
    def __str__(self):
        return self.name
# Create your models here.

lab10/firstapp/forms.py
from django.contrib.auth.models import User
from django import forms



class LoginForm(forms.Form):
    username=forms.CharField(required=True)
    password=forms.CharField(widget=forms.PasswordInput())

class CourseForm(forms.Form):
    name = forms.CharField(required=True)

class StudentForm(forms.Form):
    file = forms.FileField(required=True)
    course_name = forms.CharField(required=True)

lab10/firstapp/views.py
from .forms import *
from .models import *
from django.contrib.auth import login, logout, authenticate
from django.shortcuts import render, get_object_or_404
from django.contrib.auth.models import User
from django.http import HttpResponse
import csv
import os
from datetime import datetime   

def my_login(request):
    if request.method=="POST":
        form = LoginForm(request.POST)
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(username=username, password=password)
        if user is not None:
            login(request, user)
            all_courses=courses.objects.all();
            if user.is_superuser:
                return render(request, 'instr_home.html', {'user': user, 'allC':all_courses, 'superU':True})   
            else:
                return render(request, 'instr_home.html', {'user': user, 'allC':all_courses, 'superU':False})      
        else:
            return render(request, 'error.html', {'errorM':"Wrong Username or Password", 'link':"http://localhost:8014/firstapp/login", 'butt':"Try Again"})

    else:
        if request.user.is_authenticated:  ## Does not allow two users to log in the same session (whatever that means!)
            all_courses=courses.objects.all;
            if request.user.is_superuser:
                return render(request, 'instr_home.html', {'user': request.user, 'allC':all_courses, 'superU':True})   
            else:
                return render(request, 'instr_home.html', {'user': request.user, 'allC':all_courses, 'superU':False})
        else:
            form1=LoginForm();
            return render(request, 'login.html', {'form':form1})

def my_logout(request):
    logout(request)
    return render(request, 'error.html', {'errorM':"Logged Out Successfully", 'link':"http://localhost:8014/firstapp/login", 'butt':"Log In Again"})

def add_course(request):
    if request.user.is_authenticated:
        if request.user.is_superuser:
            if request.method =='POST':
                form = CourseForm(request.POST)
                if form.is_valid():
                    cname=form.cleaned_data['name']
                    courseCheck = courses.objects.filter(course_name=cname)
                    if courseCheck.count() == 0:
                        courses.objects.create(course_name=cname)
                        x = "Mid Sem"
                        y = "End Sem"
                        Questio.objects.create(question_id=1,forname=x,question_text="Rate the difficulty of questions", course_name=cname)
                        Questio.objects.create(question_id=2,forname=x,question_text="Rate the ", course_name=cname)
                        Questio.objects.create(question_id=1,forname=y,question_text="Rate the difficulty of questions", course_name=cname)
                        Questio.objects.create(question_id=2,forname=y,question_text="Rate the ", course_name=cname)
                        FeedbackForm.objects.create(name= x,course_name=cname)
                        FeedbackForm.objects.create(name= y,course_name=cname)
                        Deadline.objects.create(name=x, description="A new deadline")
                        Deadline.objects.create(name=y, description="A new deadline")
                        form1 = StudentForm()
                        return render(request, 'add_students.html', {'course_name':cname, 'form': form1})
                    else:
                        return render(request, 'error.html', {'errorM':"Course Already Exists!", 'link':"http://localhost:8014/firstapp/Course_reg/", 'butt':"Try Again"})
                else:
                    return render(request, 'error.html', {'errorM':"Something Went Wrong!", 'link':"http://localhost:8014/firstapp/Course_reg/", 'butt':"Try Again"})
            else:
                form = CourseForm() 
                return render(request, 'add_course.html', {'form': form})
        else:
            return render(request, 'error.html', {'errorM':"Access Denied", 'link':"http://localhost:8014/firstapp/login", 'butt':"Home"})
    else:
        return render(request, 'error.html', {'errorM':"Log-In First ;)", 'link':"http://localhost:8014/firstapp/login", 'butt':"This Way!"})

def add_students(request):
    if request.user.is_authenticated:
        if request.user.is_superuser:
            if request.method =='POST':
                form = StudentForm(request.POST, request.FILES)
                if form.is_valid():
                    courseN = form.cleaned_data['course_name']
                    r=courses.objects.filter(course_name=courseN)
                    if(r.count()!=0):
                        f = request.FILES['file']
                        with open("cor.csv", 'wb+') as destination:
                            for chunk in f.chunks():
                                    destination.write(chunk)
                        add_csv_students(courseN)
                        os.remove("cor.csv")
                        return render(request, 'error.html', {'errorM':"Students Successfully Added!", 'link':"http://localhost:8014/firstapp/login", 'butt':"Home"})

                    else:
                        return render(request, 'error.html', {'errorM':"404 Course Doesn't Exist", 'link':"http://localhost:8014/firstapp/Course_reg", 'butt':"Add This"})     
                else:
                    return render(request, 'error.html', {'errorM':"Something Went Wrong!", 'link':"http://localhost:8014/firstapp/login", 'butt':"Home"})     
            else:
                form1 = StudentForm()
                return render(request, 'add_students.html', {'form': form1})
        else:
            return render(request, 'error.html', {'errorM':"Access Denied", 'link':"http://localhost:8014/firstapp/login", 'butt':"Home"})
    else:
        return render(request, 'error.html', {'errorM':"Log-In First ;)", 'link':"http://localhost:8014/firstapp/login", 'butt':"This Way!"})
        
def add_csv_students(cname):
    with open('cor.csv') as g:
        reader = csv.reader(g,delimiter = ',')
        rows = list(reader)
    for row in rows:
        sname =row[0];
        sroll = row[1];
        adds(sname, cname, sroll)

def adds(sname,cname,sroll):
    r = courses.objects.filter(course_name=cname)
    v = Student.objects.filter(name=sname).filter(roll_number=sroll)
    if(v.count()!=0): 
        for stu in v:
            for course in r:
                stu.courses_undertaken.add(course)
    else:
        for course in r:
            Sudent=Student.objects.create(name=sname,roll_number=sroll)
            Sudent.courses_undertaken.add(course)

lab10/firstapp/templates/add_course.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <title>{{user.username}} :: Add Course</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  <link rel="stylesheet" type="text/css" href="{% static 'firstapp/style.css' %}" />

</head>

<style type="text/css">
 td{
  text-align: left;
  padding-left: 110px;
 }
 .al{
  padding-left: 20px;
 }
</style>

<body onload="init()">
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand active" href="#">Feeder14</a>
    </div>
    <ul class="nav navbar-nav">
    <li><a href="/firstapp/login/">Home</a></li>
      <li class="active"><a href="/firstapp/Course_reg/">Add a new Course</a></li>
      <li><a href="/firstapp/add_students/">Add Students</a></li>
    </ul>
    <ul class="nav navbar-nav navbar-right">
      <li><a href=""><span class="glyphicon glyphicon-user"></span>{{user.first_name}} {{user.last_name}}</a></li>
      <li><a href="/firstapp/logout/"><span class="glyphicon glyphicon-log-out"></span>Logout</a></li>
    </ul>
  </div>
</nav>
<br><br><br><br>

<div class="col-sm-4">
</div>
<div class="jumbotron col-sm-4 mm ">
<form id= "fform" method="post" action="">
  {% csrf_token %}
  <table>
  <td class="al"><span class="entypo-user "></span>
    {{form.name}}
    </td>
  </table>
  <br> 
  <table>
   <td><button class="submit button" >Add Course</button></td>
   </table>
</form>

</div>
 <script >
  function init()
  {
    x = document.getElementById("fform");
    x['name'].placeholder="                    Course Name"; // do not remove these spaces(part of styling)
    x['course_name'].value="{{course_name}}";
    
    
  }
  </script>
</body>

lab10/firstapp/templates/add_students.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <title>{{user.username}} :: Add Students</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  <link rel="stylesheet" type="text/css" href="{% static 'firstapp/style.css' %}" />
</head>
<body onload= init()>

<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand active" href="#">Feeder14</a>
    </div>
    <ul class="nav navbar-nav">
    <li><a href="/firstapp/login/">Home</a></li>
      <li><a href="/firstapp/Course_reg/">Add a new Course</a></li>
      <li class="active"><a href="/firstapp/add_students/">Add Students</a></li>
    </ul>
    <ul class="nav navbar-nav navbar-right">
      <li><a href=""><span class="glyphicon glyphicon-user"></span>{{user.first_name}} {{user.last_name}}</a></li>
      <li><a href="/firstapp/logout/"><span class="glyphicon glyphicon-log-out"></span>Logout</a></li>
    </ul>
  </div>
</nav>
<br><br><br><br>
<div class="col-sm-4">
</div>
<div class="jumbotron col-sm-4 mm ">
<form id ="fform" method="post" action="" enctype="multipart/form-data" >
    {% csrf_token %}
   <!-- <table class="form-group" > -->
    
   
  
     <table> 
     <tr>
     <th class="design">File: (in csv format)</th>
     </tr>
     <tr>
      <th class="al">{{form.file}}</th>
      </tr>
     </table>
     <table>
  <td class="al"><span class="entypo-user "></span>
    {{form.course_name}}
    </td>
  </table>
   
    <br>

    <table><td class="td"><button type="submit " class="submit button" formaction="/firstapp/add_students/" >Add</button></td>
    </table>
    <br>  
</form>
</div>
<style type="text/css">
  .design{
    padding-left: 20px;
    font-size: 20px;
    color: white;
  }
  .td{
  text-align: left;
  padding-left: 110px;
 }
 .al{
  padding-left: 20px;
 }


</style>
<script>
	function init(){
		x = document.getElementById("fform");
    x['course_name'].placeholder="                 Course Name" // do not remove these spaces(part of styling)
		x['course_name'].value="{{course_name}}";
	}
</script>
</body>
</html>

lab10/firstapp/templates/error.html
<html>
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
<style>
  .jumbotron{
  	text-align :center;
  	font-size: 60px;
  }
</style>
</head>
<body>

<div class="jumbotron"><b>
{{errorM}}</b>
</div>
<div class="container-fluid">
    
    <div class="row-fluid">
      <div class="span4 offset4 text-center">
        <a type="button" class="btn btn-primary" style='color: #ffffff' align="center" href={{link}}>{{butt}}</a>
  
      </div>
    </div>
    
  </div>

</body>
</html>

lab10/firstapp/templates/instr_home.html
<!DOCTYPE html>
<html lang="en">
<head>
  <title>{{user.username}} :: Home</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</head>
<body onload="init()">

<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand active" href="#">Feeder14</a>
    </div>
    <ul class="nav navbar-nav">
    <li class="active"><a href="/firstapp/login/">Home</a></li>
      {% if not superU %}
      <li><a href="/firstapp/feed/">Add a Feedback Form</a></li>
      <li><a href="#">See Feedback Results</a></li>
      <li><a href="#">See Form Submissions</a></li>
      <li><a href="/firstapp/add_deadline/">Add a Deadline</a></li>
      <li><a href="#">See existing deadlin</a></li>
      <li><a href="/firstapp/see_courses/">View Feedback Forms</a></li>
      {% endif %}
      {%if superU %}
      <li><a href="/firstapp/Course_reg/">Add a new Course</a></li>
      <li><a href="/firstapp/add_students/">Add Students</a></li>
      {% endif %}
    </ul>
    <ul class="nav navbar-nav navbar-right">
      <li><a href=""><span class="glyphicon glyphicon-user"></span>{{user.first_name}} {{user.last_name}}</a></li>
      <li><a href="/firstapp/logout/"><span class="glyphicon glyphicon-log-out"></span>Logout</a></li>
    </ul>
  </div>
</nav>
<br><br><br>
<div class="container">
  <h2>Running Courses</h2>
  <div class="list-group">
  {% for course in allC %}
      <a  class="list-group-item">{{course.course_name}} - {{course.student_set.count}}</a>
  {% endfor %}
  {% if allC.count == 0%}
  No Courses Added Yet
  {% endif %}

  </div>
  <h id="demo"></h>
</div>

<!-- <footer>Made By Group 14</footer> -->
</body>
</html>

lab10/firstapp/templates/login.html
{% load static %}
<html>
<head>

<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
 <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
<link rel="stylesheet" type="text/css" href="{% static 'firstapp/style.css' %}" />

</head>
<body class="bodyy" onload="init()">

<div class="jumbotron  m">
<h class="t">Feeder14: Instructor Login</h><br>
</div>

<div class="col-sm-4">
<br><br>
</div>
<div class="jumbotron col-sm-4 mm">
<form id= "fform" method="post" action="">
	{% csrf_token %}
 <h2><span class="entypo-login"></span> Login</h2>
  <button class="submit"><span class="entypo-login"></span></button>
  <span class="entypo-user inputUserIcon"></span>
  {{form.username}}
  <span class="entypo-key inputPassIcon"></span>
  {{form.password}}
</form>




</div>

<script >
  function init()
  {
    x = document.getElementById("fform");
    x['username'].placeholder="Enter Username";
    x['password'].placeholder="Enter Password";
  }
  $(".user").focusin(function(){
  $(".inputUserIcon").css("color", "#e74c3c");
}).focusout(function(){
  $(".inputUserIcon").css("color", "white");
});

$(".pass").focusin(function(){
  $(".inputPassIcon").css("color", "#e74c3c");
}).focusout(function(){
  $(".inputPassIcon").css("color", "white");
});
</script>
</body>

</html>